### ISSUE TITLE
Download pdf, converted to html

### ISSUE THREAD

**Issue by RuslanKhabibullinFs** [aspose-pdf/Aspose.Pdf-for-Cloud#16]
Now it's return zip archive instead of html file. So need fixes in ApiClient.rb to use "wb" in File.open. Aspose.PDF for Ruby

**Comment by naeem244** [comment]
Hi RuslanKhabibullinFs,

Thank you for your inquiry and sharing details.

Both our Aspose.Pdf native and Cloud APIs return Zip file once convert PDF to HTML functionality is being used. It’s a defined behavior. The reason API returns ZIP file instead of HTML because HTML page normally contains multiple files e.g. .css file, .html file and attachments. You can simply unzip it to get the HTML file.
I hope this helps. If you have any further questions, please feel free to share.

Thanks,
Naeem Akram

[Aspose](http://www.aspose.com/) - File Format APIs.

[Got a Complaint? File it!](http://www.aspose.com/community/forums/aspose.complaint/539/showforum.aspx)

Keep in touch! We're on [Twitter ](http://twitter.com/#!/aspose)and [Facebook](https://www.facebook.com/pages/Aspose/21217093093)

**Comment by RuslanKhabibullinFs** [comment]
I see. But at the moment the download of the archive in the SDK for Ruby is implemented with an error. ApiClient writes a file in the "w" mode at download time. This is the reason for the exception. You need to open the file in "wb" mode. Try to convert any file into html in ruby

**Comment by RuslanKhabibullinFs** [comment]
Same for Aspose::Words (

**Comment by naeem244** [comment]
Hi RuslanKhabibullinFs,

Thank you for your inquiry and sharing details.

We are working on this issue and will  updated you as soon as issue is fixed.

Please be patient. We are sorry for the inconvenience.

Thanks,
Naeem Akram

Aspose - File Format APIs.

Got a Complaint? File it!

Keep in touch! We're on Twitter and Facebook

**Comment by naeem244** [comment]
Hi RuslanKhabibullinFs,

Our product team has just informed us that the issue you are facing has been resolved. We apologize for any inconvenience this may have caused you.

We have tested this issue at our end. However if you are still facing issue, please send us your Pdf file which you are trying to convert to HTML using our http://api.aspose.cloud/swagger/ui/index#!/v{version:apiVersion}/pdf/PdfDocument_GetDocument API.

If you have any further questions, please feel free to share.

Thanks,

Naeem Akram
Aspose - File Format APIs.

[Got a Complaint? File it!](https://www.aspose.com/community/forums/aspose.complaint/539/showforum.aspx)

Keep in touch! We're on [Twitter](https://twitter.com/aspose) and [Facebook](https://www.facebook.com/aspose/)
